TCC/force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Administrar os projetos sociais das instituições não governamentais beneficiadas pelo software</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/Projeto__c/fields/PeriodoProjeto__c.field-meta.xml
<CustomField>
    <fullName>PeriodoProjeto__c</fullName>
    <label>Período</label>
    <type>Date</type>
</CustomField>

TCC/force-app/main/default/classes/ProjetosLWCController.cls
public with sharing class ProjetosLWCController {

    @AuraEnabled
    public static List<ProjetoVO> getDadosProjetos(String recordId){
     	List<ProjetoVO> listProjetoVO = new List<ProjetoVO>();
        
        List<Projeto__c> projetos = ProjetoDAO.getProjetos(recordId);
        
        /*for(Projeto__c proj: projetos){
            listProjetoVO.add(new ProjetoVO(proj.Id, proj.Name, proj.PeriodoProjeto__c));
        }*/
        return listProjetoVO;
    }
}