TCC/TCC/force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <label>Documentação</label>
    <nameField>
        <label>Descrição da Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Atualizado</fullName>
            </value>
            <value>
                <fullName>Próximo ao Vencimento</fullName>
            </value>
            <value>
                <fullName>Desatualizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TCC/TCC/force-app/main/default/classes/DocumentacaoUtils.cls
public with sharing class DocumentacaoUtils {

    public static void updateStatus(Map<Id, Documentacao__c> mapDoc){
        
        List<Documentacao__c> listDocUpdate = new List<Documentacao__c>();
        
        for(Documentacao__c doc : mapDoc.values()){            
            Date dataAtual = System.today();
            if(dataAtual < doc.DataVencimento__c && dataAtual.addDays(7) == doc.DataVencimento__c){
                doc.Status__c = 'Próximo ao Vencimento';    
                listDocUpdate.add(doc);
            }
            else if(dataAtual < doc.DataVencimento__c){
                doc.Status__c = 'Atualizado';    
                listDocUpdate.add(doc);
            }
            else if(dataAtual >= doc.DataVencimento__c){
                doc.Status__c = 'Desatualizado';    
                listDocUpdate.add(doc);
            } 
        }
        update listDocUpdate;
    }
}