TCC/TCC/force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <label>Documentação</label>
    <nameField>
        <label>Descrição da Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/DataEmissao__c.field-meta.xml
<CustomField>
    <fullName>DataEmissao__c</fullName>
    <label>Data de Emissão do Documento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/DocumentacaoProjeto__c.field-meta.xml
<CustomField>
    <fullName>DocumentacaoProjeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documentação do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Documentação do Projeto</relationshipLabel>
    <relationshipName>Documentacao</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/TipoDocumentacao__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumentacao__c</fullName>
    <label>Tipo Documentação</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cartão do CNPJ</fullName>
            </value>
            <value>
                <fullName>Ata de Eleição</fullName>
            </value>
            <value>
                <fullName>Estatuto</fullName>
            </value>
            <value>
                <fullName>Regimento Interno</fullName>
            </value>
            <value>
                <fullName>Certificado de Regularidade Cadastral de Entidades – CRCE</fullName>
            </value>
            <value>
                <fullName>Certificado de Registro Cadastral – CRC</fullName>
            </value>
            <value>
                <fullName>Certidão Negativa de Débitos Federal (CND Federal)</fullName>
            </value>
            <value>
                <fullName>Certidão Negativa de Débitos Estadual (CND Estadual)</fullName>
            </value>
            <value>
                <fullName>Certidão Negativa de Débitos Municipal (CND Municipal)</fullName>
            </value>
            <value>
                <fullName>Outro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TCC/TCC/force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Administrar os projetos sociais das instituições não governamentais beneficiadas pelo software</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Projeto__c/fields/StatusProjeto__c.field-meta.xml
<CustomField>
    <fullName>StatusProjeto__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando Resposta</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TCC/TCC/force-app/main/default/objects/Projeto__c/fields/TipoDocumentacao__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumentacao__c</fullName>
    <label>Tipo da Documentação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoDocumentacao</valueSetName>
    </valueSet>
</CustomField>

TCC/TCC/force-app/main/default/globalValueSets/TipoDocumentacao.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cartão do CNPJ</fullName>
    </customValue>
    <customValue>
        <fullName>Ata de Eleição</fullName>
    </customValue>
    <customValue>
        <fullName>Estatuto</fullName>
    </customValue>
    <customValue>
        <fullName>Regimento Interno</fullName>
    </customValue>
    <customValue>
        <fullName>CRCE</fullName>
        <label>Certificado de Regularidade Cadastral de Entidades – CRCE</label>
    </customValue>
    <customValue>
        <fullName>CRC</fullName>
        <label>Certificado de Registro Cadastral – CRC</label>
    </customValue>
    <customValue>
        <fullName>CND Federal</fullName>
        <label>Certidão Negativa de Débitos Federal (CND Federal)</label>
    </customValue>
    <customValue>
        <fullName>CND Estadual</fullName>
        <label>Certidão Negativa de Débitos Estadual (CND Estadual)</label>
    </customValue>
    <customValue>
        <fullName>CND Municipal</fullName>
        <label>Certidão Negativa de Débitos Municipal (CND Municipal)</label>
    </customValue>
    <customValue>
        <fullName>Outro</fullName>
    </customValue>
    <masterLabel>Tipo Documentação</masterLabel>
</GlobalValueSet>

TCC/TCC/force-app/main/default/classes/DocumentacaoTriggerHandlerHelper.cls
public with sharing class DocumentacaoTriggerHandlerHelper {

    public static void setDataVencimentoDocumentacao(List<Documentacao__c> triggerNew){
        
        Documentacao__c triggerNewDoc = triggerNew.get(0);
        Documentacao__c docUpdate = [SELECT Id, DataEmissao__c, DataVencimento__c, TipoDocumentacao__c FROM Documentacao__c WHERE Id =: triggerNewDoc.Id LIMIT 1];
            
            Date dataEmissao = docUpdate.DataEmissao__c;
            
            switch on docUpdate.TipoDocumentacao__c {
                
                when 'Cartão do CNPJ'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(30);
                }
                when 'Ata de Eleição'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(40);
                }
                when 'Estatuto'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(180);
                }
                when 'Regimento Interno'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(180);
                }
                when 'CRCE'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(180);
                }
                when 'CRC'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(60);
                }
                when 'CND Federal'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(80);
                }
                when 'CND Estadual'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(100);
                }
                when 'CND Municipal'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(180);
                }
            }
        update docUpdate;
    }
    
    public static void preventAdditionWhenProjIsFinished(List<Documentacao__c> triggerNew){
    	Set<Id> idSet = new Set<Id>();

        if(triggerNew != null){
            for(Documentacao__c doc : triggerNew){
                if(doc.DocumentacaoProjeto__c != null)
                    idSet.add(doc.DocumentacaoProjeto__c);
          	}
    	}
        
        List<Projeto__c> projList = [SELECT Id, StatusProjeto__c FROM Projeto__c WHERE Id IN: idSet];
        Map<Id, String> idVsStatus = new map<Id, String>();
        
        for(Projeto__c proj : projList){
            if(!idVsStatus.containsKey(proj.Id))
                idVsStatus.put(proj.Id, proj.StatusProjeto__c);
        }
        
        for(Documentacao__c doc : triggerNew){
            if(idVsStatus.get(doc.DocumentacaoProjeto__c) == 'Finalizado' || idVsStatus.get(doc.DocumentacaoProjeto__c) == 'Cancelado')
                doc.addError('Não é possível adicionar uma Documentação com o Projeto no status atual');
        }
    }
}