TCC/TCC/force-app/main/default/objects/FluxoCaixa__c/FluxoCaixa__c.object-meta.xml
<CustomObject>
    <label>Fluxo de Caixa</label>
    <nameField>
        <label>Fluxo de Caixa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fluxo de Caixa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/FluxoCaixa__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <label>Mes</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Receitas__c/Receitas__c.object-meta.xml
<CustomObject>
    <label>Receita</label>
    <nameField>
        <label>Receitas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/Receitas__c/fields/DataReceita__c.field-meta.xml
<CustomField>
    <fullName>DataReceita__c</fullName>
    <label>Data do Recebimento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Receitas__c/fields/FluxoCaixa__c.field-meta.xml
<CustomField>
    <fullName>FluxoCaixa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fluxo de Caixa</label>
    <referenceTo>FluxoCaixa__c</referenceTo>
    <relationshipLabel>Receitas</relationshipLabel>
    <relationshipName>Receitas</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/classes/ReceitasTriggerHandlerHelper.cls
public with sharing class ReceitasTriggerHandlerHelper {
    
    public static void fillMonthField(List<Receitas__c> triggerNew){

        Integer mesReceita;
        
        List<Receitas__c> rList = [SELECT Id, Mes__c, DataReceita__c FROM Receitas__c WHERE Id IN: triggerNew];
        List<Receitas__c> rToUpdate = new List<Receitas__c>();

        for(Receitas__c receita : rList){
            mesReceita = receita.DataReceita__c.month();
            receita.Mes__c = mesReceita;

            rToUpdate.add(receita);
        }
        update rToUpdate;
    }
    
    public static void insertInFluxoCaixa(List<Receitas__c> triggerNew){
        FluxoCaixa__c fluxo = [SELECT Id FROM FluxoCaixa__c LIMIT 1];
        
        for(Receitas__c r : triggerNew){
			r.FluxoCaixa__c = fluxo.Id;
        }
    }
}