TCC/TCC/force-app/main/default/objects/Despesas__c/Despesas__c.object-meta.xml
<CustomObject>
    <label>Despesa</label>
    <nameField>
        <label>Despesa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/DataDespesa__c.field-meta.xml
<CustomField>
    <fullName>DataDespesa__c</fullName>
    <label>Data da Despesa</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/DespesasPlanilhaOrcamentaria__c.field-meta.xml
<CustomField>
    <fullName>DespesasPlanilhaOrcamentaria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Planilha Orçamentária</label>
    <referenceTo>PlanilhaOrcamentaria__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/force-app/main/default/objects/Despesas__c/fields/DespesasProjeto__c.field-meta.xml
<CustomField>
    <fullName>DespesasProjeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Despesas do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Despesas do Projeto</relationshipLabel>
    <relationshipName>DespesasProjeto</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/FluxoCaixa__c.field-meta.xml
<CustomField>
    <fullName>FluxoCaixa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fluxo de Caixa</label>
    <referenceTo>FluxoCaixa__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/FluxoCaixa__c/FluxoCaixa__c.object-meta.xml
<CustomObject>
    <label>Fluxo de Caixa</label>
    <nameField>
        <label>Fluxo de Caixa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fluxo de Caixa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/FluxoCaixa__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <label>Mes</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/PlanilhaOrcamentaria__c.object-meta.xml
<CustomObject>
    <description>Planilhas orçamentárias presentes em cada projeto</description>
    <label>Planilha Orçamentária</label>
    <nameField>
        <label>Planilha Orçamentária</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planilhas Orçamentárias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/fields/PlanilhaOrcamentariaProjeto__c.field-meta.xml
<CustomField>
    <fullName>PlanilhaOrcamentariaProjeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Planilha Orçamentária do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Planilha Orcamentária do Projeto</relationshipLabel>
    <relationshipName>PlanilhaOrcamentariaProjeto</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Administrar os projetos sociais das instituições não governamentais beneficiadas pelo software</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Projeto__c/fields/StatusProjeto__c.field-meta.xml
<CustomField>
    <fullName>StatusProjeto__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando Resposta</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TCC/TCC/force-app/main/default/classes/DespesasTriggerHandlerHelper.cls
public with sharing class DespesasTriggerHandlerHelper {
    
    public static void fillMonthField(List<Despesas__c> triggerNew){

        Integer mesReceita;
        
        List<Despesas__c> dList = [SELECT Id, Mes__c, DataDespesa__c FROM Despesas__c WHERE Id IN: triggerNew];
        List<Despesas__c> dToUpdate = new List<Despesas__c>();

        for(Despesas__c Despesa : dList){
            mesReceita = Despesa.DataDespesa__c.month();
            Despesa.Mes__c = mesReceita;

            dToUpdate.add(Despesa);
        }
        update dToUpdate;
    }
    
    public static void insertInFluxoCaixa(List<Despesas__c> triggerNew){
        FluxoCaixa__c fluxo = [SELECT Id FROM FluxoCaixa__c LIMIT 1];
        
        for(Despesas__c d : triggerNew){
			d.FluxoCaixa__c = fluxo.Id;
        }
    }
    
    public static void insertInPlanilhaOrcamentaria(List<Despesas__c> triggerNew){
        Id idProj = triggerNew.get(0).DespesasProjeto__c ;
        PlanilhaOrcamentaria__c po = [SELECT Id, PlanilhaOrcamentariaProjeto__c FROM PlanilhaOrcamentaria__c WHERE PlanilhaOrcamentariaProjeto__c =: idProj LIMIT 1];
        for(Despesas__c d : triggerNew){
            if(d.DespesasProjeto__c != null){
                d.DespesasPlanilhaOrcamentaria__c = po.Id;
            }
        }
    }
    
     public static void preventAdditionWhenProjIsFinished(List<Despesas__c> triggerNew){
    	Set<Id> idSet = new Set<Id>();

        if(triggerNew != null){
            for(Despesas__c desp : triggerNew){
                if(desp.DespesasProjeto__c != null)
                    idSet.add(desp.DespesasProjeto__c);
          	}
    	}
        
        List<Projeto__c> projList = [SELECT Id, StatusProjeto__c FROM Projeto__c WHERE Id IN: idSet];
        Map<Id, String> idVsStatus = new map<Id, String>();
        
        for(Projeto__c proj : projList){
            if(!idVsStatus.containsKey(proj.Id))
                idVsStatus.put(proj.Id, proj.StatusProjeto__c);
        }
        
        for(Despesas__c desp : triggerNew){
            if(idVsStatus.get(desp.DespesasProjeto__c) == 'Finalizado' || idVsStatus.get(desp.DespesasProjeto__c) == 'Cancelado')
                desp.addError('Não é possível cadastrar uma nova Despesa com o Projeto no status atual');
        }
    }
}