TCC/TCC/force-app/main/default/objects/Despesas__c/Despesas__c.object-meta.xml
<CustomObject>
    <label>Despesa</label>
    <nameField>
        <label>Despesa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/DataDespesa__c.field-meta.xml
<CustomField>
    <fullName>DataDespesa__c</fullName>
    <label>Data da Despesa</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Destinação</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/DespesasPlanilhaOrcamentaria__c.field-meta.xml
<CustomField>
    <fullName>DespesasPlanilhaOrcamentaria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Planilha Orçamentária</label>
    <referenceTo>PlanilhaOrcamentaria__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/force-app/main/default/objects/Despesas__c/fields/DespesasProjeto__c.field-meta.xml
<CustomField>
    <fullName>DespesasProjeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Despesas do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Despesas do Projeto</relationshipLabel>
    <relationshipName>DespesasProjeto</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/ValorDespesa__c.field-meta.xml
<CustomField>
    <fullName>ValorDespesa__c</fullName>
    <label>Valor da Despesa</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/PlanilhaOrcamentaria__c.object-meta.xml
<CustomObject>
    <description>Planilhas orçamentárias presentes em cada projeto</description>
    <label>Planilha Orçamentária</label>
    <nameField>
        <label>Planilha Orçamentária</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planilhas Orçamentárias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição da Planilha Orçamentária</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Administrar os projetos sociais das instituições não governamentais beneficiadas pelo software</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/Projeto__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

TCC/TCC/force-app/main/default/classes/DespesasDAO.cls
public with sharing class DespesasDAO implements DAO {

    public static List<Despesas__c> get(String recordId){
        return [SELECT Id, Name, DataDespesa__c, Descricao__c, DespesasPlanilhaOrcamentaria__r.Name, DespesasProjeto__r.Name, DespesasProjeto__c, DespesasPlanilhaOrcamentaria__c, ValorDespesa__c FROM Despesas__c WHERE Id =: recordId];
    }
    
    public static List<Despesas__c> getAllByMonth(Decimal mes){
    	return [SELECT Id, ValorDespesa__c, Mes__c FROM Despesas__c WHERE Mes__c =: mes];
    }

    public static List<Despesas__c> getAll(){
    	return [SELECT Id, ValorDespesa__c FROM Despesas__c];
    }
}