TCC/force-app/main/default/objects/Despesas__c/Despesas__c.object-meta.xml
<CustomObject>
    <label>Despesa</label>
    <nameField>
        <label>Despesa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/DataDespesa__c.field-meta.xml
<CustomField>
    <fullName>DataDespesa__c</fullName>
    <label>Data da Despesa</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/FluxoCaixa__c.field-meta.xml
<CustomField>
    <fullName>FluxoCaixa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fluxo de Caixa</label>
    <referenceTo>FluxoCaixa__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/force-app/main/default/objects/FluxoCaixa__c/FluxoCaixa__c.object-meta.xml
<CustomObject>
    <label>Fluxo de Caixa</label>
    <nameField>
        <label>Fluxo de Caixa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fluxos de Caixa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/FluxoCaixa__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <label>Mes</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TCC/force-app/main/default/classes/DespesasTriggerHandlerHelper.cls
public with sharing class DespesasTriggerHandlerHelper {
    
    public static void fillMonthField(List<Despesas__c> triggerNew){

        Integer mesReceita;
        
        List<Despesas__c> dList = [SELECT Id, Mes__c, DataDespesa__c FROM Despesas__c WHERE Id IN: triggerNew];
        List<Despesas__c> dToUpdate = new List<Despesas__c>();

        for(Despesas__c Despesa : dList){
            mesReceita = Despesa.DataDespesa__c.month();
            Despesa.Mes__c = mesReceita;

            dToUpdate.add(Despesa);
        }
        update dToUpdate;
    }
    
    public static void insertInFluxoCaixa(List<Despesas__c> triggerNew){
        FluxoCaixa__c fluxo = [SELECT Id FROM FluxoCaixa__c LIMIT 1];
        
        for(Despesas__c d : triggerNew){
			d.FluxoCaixa__c = fluxo.Id;
        }
    }
}