TCC/force-app/main/default/objects/Despesas__c/Despesas__c.object-meta.xml
<CustomObject>
    <label>Despesa</label>
    <nameField>
        <label>Despesa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/ValorDespesa__c.field-meta.xml
<CustomField>
    <fullName>ValorDespesa__c</fullName>
    <label>Valor da Despesa</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

TCC/force-app/main/default/objects/Receitas__c/Receitas__c.object-meta.xml
<CustomObject>
    <label>Receita</label>
    <nameField>
        <label>Receitas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Receitas__c/fields/ValorReceita__c.field-meta.xml
<CustomField>
    <fullName>ValorReceita__c</fullName>
    <label>Valor da Receita</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

TCC/force-app/main/default/classes/FluxoCaixaLWCController.cls
public with sharing class FluxoCaixaLWCController {

    @AuraEnabled
    public static List<Receitas__c> getReceitas(Decimal mes){
        return [SELECT Id, ValorReceita__c, Mes__c FROM Receitas__c WHERE Mes__c =: mes];
    }
    
    @AuraEnabled
    public static List<Despesas__c> getDespesas(Decimal mes){
        return [SELECT Id, ValorDespesa__c, Mes__c FROM Despesas__c WHERE Mes__c =: mes];
    }
}