TCC/force-app/main/default/objects/Despesas__c/Despesas__c.object-meta.xml
<CustomObject>
    <label>Despesa</label>
    <nameField>
        <label>Despesa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/DataDespesa__c.field-meta.xml
<CustomField>
    <fullName>DataDespesa__c</fullName>
    <label>Data da Despesa</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Destinação</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TCC/force-app/main/default/objects/Despesas__c/fields/DespesasPlanilhaOrcamentaria__c.field-meta.xml
<CustomField>
    <fullName>DespesasPlanilhaOrcamentaria__c</fullName>
    <label>Planilha Orçamentária</label>
    <referenceTo>PlanilhaOrcamentaria__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TCC/force-app/main/default/objects/Despesas__c/fields/DespesasProjeto__c.field-meta.xml
<CustomField>
    <fullName>DespesasProjeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Despesas do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Despesas do Projeto</relationshipLabel>
    <relationshipName>DespesasProjeto</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/ValorDespesa__c.field-meta.xml
<CustomField>
    <fullName>ValorDespesa__c</fullName>
    <label>Valor da Despesa</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/PlanilhaOrcamentaria__c.object-meta.xml
<CustomObject>
    <description>Planilhas orçamentárias presentes em cada projeto</description>
    <label>Planilha Orçamentária</label>
    <nameField>
        <label>Planilha Orçamentária</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planilhas Orçamentárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição da Planilha Orçamentária</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

TCC/force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Administrar os projetos sociais das instituições não governamentais beneficiadas pelo software</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/Projeto__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

TCC/force-app/main/default/classes/DespesasLWCController.cls
public with sharing class DespesasLWCController {

    @AuraEnabled
    public static List<DespesasVO> getDespesas(String recordId){
        List<Despesas__c> listDespesas = DespesasDAO.get(recordId);
        List<DespesasVO> listDespesasVO = new List<DespesasVO>();
        
        String urlDomain = Url.getOrgDomainUrl().toExternalForm();
        
        for(Despesas__c desp: listDespesas){
            listDespesasVO.add(new DespesasVO(desp.Id, desp.Descricao__c, desp.DataDespesa__c, desp.ValorDespesa__c,
            desp.DespesasPlanilhaOrcamentaria__c, desp.DespesasPlanilhaOrcamentaria__r.Name, desp.DespesasProjeto__c, desp.DespesasProjeto__r.Name, urlDomain));
        }
        return listDespesasVO;
    }
}