TCC/force-app/main/default/objects/Despesas__c/Despesas__c.object-meta.xml
<CustomObject>
    <label>Despesa</label>
    <nameField>
        <label>Despesa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Despesas__c/fields/ValorDespesa__c.field-meta.xml
<CustomField>
    <fullName>ValorDespesa__c</fullName>
    <label>Valor da Despesa</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

TCC/force-app/main/default/classes/DespesasTriggerHandlerHelperTest.cls
@isTest
private class DespesasTriggerHandlerHelperTest {

    @testSetup
    static void makeData(){
        insert TestDataFactory.makeDespesa();
    }
    
    @isTest
    static void fillMonthFieldTest(){
        
        List<Despesas__c> listDesp = [SELECT Id, Mes__c, ValorDespesa__c FROM Despesas__c];
        
        Test.startTest();
        DespesasTriggerHandlerHelper.fillMonthField(listDesp);
        Test.stopTest();
    }
}