TCC/force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <label>Documentação</label>
    <nameField>
        <label>Nome da Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/DataEmissao__c.field-meta.xml
<CustomField>
    <fullName>DataEmissao__c</fullName>
    <label>Data de Emissão do Documento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/TipoDocumentacao__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumentacao__c</fullName>
    <label>Tipo Documentação</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cartão do CNPJ</fullName>
            </value>
            <value>
                <fullName>Ata de Eleição</fullName>
            </value>
            <value>
                <fullName>Estatuto</fullName>
            </value>
            <value>
                <fullName>Regimento Interno</fullName>
            </value>
            <value>
                <fullName>Certificado de Regularidade Cadastral de Entidades – CRCE</fullName>
            </value>
            <value>
                <fullName>Certificado de Registro Cadastral – CRC</fullName>
            </value>
            <value>
                <fullName>Certidão Negativa de Débitos Federal (CND Federal)</fullName>
            </value>
            <value>
                <fullName>Certidão Negativa de Débitos Estadual (CND Estadual)</fullName>
            </value>
            <value>
                <fullName>Certidão Negativa de Débitos Municipal (CND Municipal)</fullName>
            </value>
            <value>
                <fullName>Outro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TCC/force-app/main/default/classes/DocumentacaoTriggerHandlerHelper.cls
public with sharing class DocumentacaoTriggerHandlerHelper {

    public static void setDataVencimentoDocumentacao(List<Documentacao__c> triggerNew){
        
        Documentacao__c triggerNewDoc = triggerNew.get(0);
        Documentacao__c docUpdate = [SELECT Id, DataEmissao__c, DataVencimento__c, TipoDocumentacao__c FROM Documentacao__c WHERE Id =: triggerNewDoc.Id LIMIT 1];
            
            Date dataEmissao = docUpdate.DataEmissao__c;
            
            switch on docUpdate.TipoDocumentacao__c {
                
                when 'Cartão do CNPJ'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(30);
                }
                when 'Ata de Eleição'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(40);
                }
                when 'Estatuto'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(180);
                }
                when 'Regimento Interno'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(180);
                }
                when 'CRCE'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(180);
                }
                when 'CRC'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(60);
                }
                when 'CND Federal'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(80);
                }
                when 'CND Estadual'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(100);
                }
                when 'CND Municipal'{
                    docUpdate.DataVencimento__c = dataEmissao.addDays(180);
                }
            }
        update docUpdate;
    }
}