TCC/force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <label>Documentação</label>
    <nameField>
        <label>Nome da Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/DataEmissao__c.field-meta.xml
<CustomField>
    <fullName>DataEmissao__c</fullName>
    <label>Data de Emissão do Documento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Atualizado</fullName>
            </value>
            <value>
                <fullName>Próximo ao Vencimento</fullName>
            </value>
            <value>
                <fullName>Desatualizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TCC/force-app/main/default/classes/DocumentacaoScheduler.cls
global with sharing class DocumentacaoScheduler implements Schedulable {
    
    public static String scheduleDaily = '0 0 1 * * ?'; // roda todo dia uma da manhã

    global void execute(SchedulableContext SC){
        List<Documentacao__c> listDoc = [SELECT Id, DataEmissao__c, DataVencimento__c, Status__c FROM Documentacao__c];
        
        if(!listDoc.isEmpty())
            DocumentacaoUtils.updateStatus(listDoc);
    }
    
    /*global static String scheduleEveryDay(){
        return System.schedule('schedule for updating doc status', scheduleDaily, new DocumentacaoScheduler());
    }*/
}