TCC/force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <label>Documentação</label>
    <nameField>
        <label>Nome da Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/DataEmissao__c.field-meta.xml
<CustomField>
    <fullName>DataEmissao__c</fullName>
    <label>Data de Emissão do Documento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/DocumentacaoProjeto__c.field-meta.xml
<CustomField>
    <fullName>DocumentacaoProjeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documentação do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Documentação do Projeto</relationshipLabel>
    <relationshipName>Documentacao</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/NomeOSC__c.field-meta.xml
<CustomField>
    <fullName>NomeOSC__c</fullName>
    <label>OSC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Atualizado</fullName>
            </value>
            <value>
                <fullName>Próximo ao Vencimento</fullName>
            </value>
            <value>
                <fullName>Desatualizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TCC/force-app/main/default/objects/Documentacao__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo Documentação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoDocumentacao</valueSetName>
    </valueSet>
</CustomField>

TCC/force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Administrar os projetos sociais das instituições não governamentais beneficiadas pelo software</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/Projeto__c/fields/DataInicioProjeto__c.field-meta.xml
<CustomField>
    <fullName>DataInicioProjeto__c</fullName>
    <label>Data de Início do Projeto</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/force-app/main/default/globalValueSets/TipoDocumentacao.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CNPJ</fullName>
    </customValue>
    <masterLabel>Tipo Documentação</masterLabel>
</GlobalValueSet>

TCC/force-app/main/default/classes/TestDataFactory.cls
/*
 * classe responsável por gerar dados para as classes de teste 
 */

@isTest
public class TestDataFactory {

    public static Documentacao__c makeDocumentacao(){
        Projeto__c proj = new Projeto__c();
        proj.DataInicioProjeto__c = System.today() - 1;
        insert proj;
        
        Documentacao__c doc = new Documentacao__c();
        doc.Tipo__c = 'Estatuto';
        doc.DataEmissao__c = System.today();
        doc.NomeOSC__c = 'osc';
        doc.DocumentacaoProjeto__c = proj.Id;
        doc.Name = 'teste';
        doc.Status__c = 'Atualizado';
        doc.DataVencimento__c = System.today() + 30;
        
        return doc;
    }
    
    public static Documentacao__c makeDocumentacao(Projeto__c proj){
        Documentacao__c doc = new Documentacao__c();
        doc.Tipo__c = 'Estatuto';
        doc.DataEmissao__c = System.today();
        doc.NomeOSC__c = 'osc';
        doc.DocumentacaoProjeto__c = proj.Id;
        doc.Name = 'teste';
        doc.Status__c = 'Atualizado';
        doc.DataVencimento__c = System.today() + 30;
        
        return doc;
    }
}