TCC/force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <label>Documentação</label>
    <nameField>
        <label>Nome da Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Atualizado</fullName>
            </value>
            <value>
                <fullName>Próximo ao Vencimento</fullName>
            </value>
            <value>
                <fullName>Desatualizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TCC/force-app/main/default/classes/DocumentacaoUtils.cls
public with sharing class DocumentacaoUtils {

    public static void updateStatus(List<Documentacao__c> listDoc){
        
        List<Documentacao__c> listDocUpdate = new List<Documentacao__c>();
        
        for(Documentacao__c doc : listDoc){
            
            Date dataVencimento = doc.DataVencimento__c;
            Integer diaVencimento = dataVencimento.day();
            Integer mesVencimento = dataVencimento.month();
            Integer anoVencimento = dataVencimento.year();
            
            Date dataAtual = System.today();
            Integer diaAtual = dataAtual.day();
            Integer mesAtual = dataAtual.month();
            Integer anoAtual = dataAtual.year();
            
            if(anoAtual < anoVencimento){
                doc.Status__c = 'Atualizado';    
                listDocUpdate.add(doc);
            }else if(anoAtual > anoVencimento){
                doc.Status__c = 'Desatualizado';    
                listDocUpdate.add(doc);
            }else if(dataAtual < dataVencimento && dataAtual.addDays(7) == dataVencimento){
                doc.Status__c = 'Próximo ao Vencimento';    
                listDocUpdate.add(doc);
            }else if(dataAtual < dataVencimento){
                doc.Status__c = 'Atualizado';    
                listDocUpdate.add(doc);
            }else if(dataAtual >= dataVencimento){
				doc.Status__c = 'Desatualizado';    
                listDocUpdate.add(doc);
            }
        }
        update listDocUpdate;
    }
}