TCC/force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <label>Documentação</label>
    <nameField>
        <label>Nome da Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/DataEmissao__c.field-meta.xml
<CustomField>
    <fullName>DataEmissao__c</fullName>
    <label>Data de Emissão do Documento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/DocumentacaoProjeto__c.field-meta.xml
<CustomField>
    <fullName>DocumentacaoProjeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documentação do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Documentação do Projeto</relationshipLabel>
    <relationshipName>Documentacao</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/OutroTipoDocumentacao__c.field-meta.xml
<CustomField>
    <fullName>OutroTipoDocumentacao__c</fullName>
    <label>Outro Tipo de Documentação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

TCC/force-app/main/default/objects/Documentacao__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo Documentação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoDocumentacao</valueSetName>
    </valueSet>
</CustomField>

TCC/force-app/main/default/globalValueSets/TipoDocumentacao.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CNPJ</fullName>
    </customValue>
    <masterLabel>Tipo Documentação</masterLabel>
</GlobalValueSet>

TCC/force-app/main/default/classes/InvocableInsertDocumentacao.cls
public with sharing class InvocableInsertDocumentacao {
    
    static Output o = new Output();

    @InvocableMethod
    public static List<Output> insertDocumentacao(List<Input> flowInputs){
        Input i = flowInputs.get(0);
        
        Documentacao__c d = new Documentacao__c(Name = i.descricaoDocumentacao, 
                                           	   DataEmissao__c = i.dataEmissao,
                                               DataVencimento__c = i.dataVencimento,
                                               Tipo__c = i.tipo,
                                               OutroTipoDocumentacao__c = i.descricaoOutro,
                                               DocumentacaoProjeto__c = i.projetoRelacionado);
        insert d;
        
        o.idNewDocumentacao = d.Id;
        
        return new List<Output>{o};
    }
    
    public static String getId(){
        return o.idNewDocumentacao;
    }
    
    public class Input{
        @InvocableVariable
        public String descricaoDocumentacao;
        
        @InvocableVariable
        public Date dataEmissao;
        
        @InvocableVariable
        public Date dataVencimento;
        
        @InvocableVariable
        public String tipo;
        
        @InvocableVariable
        public String descricaoOutro;
        
        @InvocableVariable
        public String projetoRelacionado;
    }
    
    public class Output{
        @InvocableVariable
        public String idNewDocumentacao;
    }
}