TCC/force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <label>Documentação</label>
    <nameField>
        <label>Nome da Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Atualizado</fullName>
            </value>
            <value>
                <fullName>Próximo ao Vencimento</fullName>
            </value>
            <value>
                <fullName>Desatualizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TCC/force-app/main/default/objects/FluxoCaixa__c/FluxoCaixa__c.object-meta.xml
<CustomObject>
    <label>Fluxo de Caixa</label>
    <nameField>
        <label>Fluxo de Caixa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fluxos de Caixa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Administrar os projetos sociais das instituições não governamentais beneficiadas pelo software</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/classes/HomePageLWCController.cls
public with sharing class HomePageLWCController {

    @AuraEnabled(cacheable=true)
    public static Integer getNumberOfProjetos(){
        return [SELECT COUNT() FROM Projeto__c];
    }
    
    @AuraEnabled(cacheable=true)
    public static Integer getDocsToUpdate(){
        return [SELECT COUNT() FROM Documentacao__c WHERE Status__c != 'Atualizado'];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<FluxoCaixaVO> getFluxoCaixaInfo(){
        String inutil = 'a';
        List<FluxoCaixa__c> fluxo = FluxoCaixaDAO.get(inutil);
        List<FluxoCaixaVO> ret = new List<FluxoCaixaVO>();
		String urlDomain = Url.getOrgDomainUrl().toExternalForm();
        
        for(FluxoCaixa__c f : fluxo)
            ret.add(new FluxoCaixaVO(f.Id, f.Name, urlDomain));
		
        return ret;
    }
}