TCC/force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <label>Documentação</label>
    <nameField>
        <label>Nome da Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Atualizado</fullName>
            </value>
            <value>
                <fullName>Próximo ao Vencimento</fullName>
            </value>
            <value>
                <fullName>Desatualizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TCC/force-app/main/default/classes/DocumentacaoUtilsTest.cls
@isTest
private class DocumentacaoUtilsTest {
    
    @testSetup
    static void makeData(){
        
       Date currentDate = System.today();
        
       Documentacao__c docVencida = TestDataFactory.makeDocumentacao();
       insert docVencida;
        
       Documentacao__c docEmDia = TestDataFactory.makeDocumentacao();
       insert docEmDia;
        
       Documentacao__c docAVencer = TestDataFactory.makeDocumentacao();
       insert docAVencer;
        
       docVencida.DataVencimento__c = currentDate - 1;
       update docVencida;
        
       docEmDia.DataVencimento__c = currentDate + 1;
       update docEmDia;
    }
    
    @isTest
    static void updateStatusTest(){
        
        List<Documentacao__c> listDoc = [SELECT Id, DataVencimento__c, Status__c FROM Documentacao__c];
        
        Test.startTest();
        DocumentacaoUtils.updateStatus(listDoc);
        Test.stopTest();
    }
}