TCC/force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <label>Documentação</label>
    <nameField>
        <label>Nome da Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/DocumentacaoProjeto__c.field-meta.xml
<CustomField>
    <fullName>DocumentacaoProjeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documentação do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Documentação do Projeto</relationshipLabel>
    <relationshipName>Documentacao</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/NomeOSC__c.field-meta.xml
<CustomField>
    <fullName>NomeOSC__c</fullName>
    <label>OSC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Documentacao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Atualizado</fullName>
            </value>
            <value>
                <fullName>Próximo ao Vencimento</fullName>
            </value>
            <value>
                <fullName>Desatualizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TCC/force-app/main/default/objects/Documentacao__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo Documentação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoDocumentacao</valueSetName>
    </valueSet>
</CustomField>

TCC/force-app/main/default/globalValueSets/TipoDocumentacao.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CNPJ</fullName>
    </customValue>
    <masterLabel>Tipo Documentação</masterLabel>
</GlobalValueSet>

TCC/force-app/main/default/classes/DocumentacaoLWCController.cls
public with sharing class DocumentacaoLWCController {

    @AuraEnabled
    public static List<DocumentacaoVO> getDocumentacao(String recordId){
        
        List<Documentacao__c> docs = DocumentacaoDAO.getDocumentacoes(recordId);
        List<DocumentacaoVO> docsToDisplay = new List<DocumentacaoVO>();
        
        for(Documentacao__c doc: docs){
            docsToDisplay.add(new DocumentacaoVO(doc.Id, doc.nomeOSC__c, doc.DocumentacaoProjeto__c, doc.Name, doc.Tipo__c, doc.DataVencimento__c, doc.Status__c));
        }
        return docsToDisplay;
	}
}