TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/PlanilhaOrcamentaria__c.object-meta.xml
<CustomObject>
    <description>Planilhas orçamentárias presentes em cada projeto</description>
    <label>Planilha Orçamentária</label>
    <nameField>
        <label>Planilha Orçamentária</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planilhas Orçamentárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/fields/PlanilhaOrcamentariaProjeto__c.field-meta.xml
<CustomField>
    <fullName>PlanilhaOrcamentariaProjeto__c</fullName>
    <label>Planilha Orçamentária do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Planilha Orcamentária do Projeto</relationshipLabel>
    <relationshipName>PlanilhaOrcamentariaProjeto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TCC/force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Administrar os projetos sociais das instituições não governamentais beneficiadas pelo software</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/classes/PlanilhaOrcamentariaTriggerHandlerHelper.cls
public with sharing class PlanilhaOrcamentariaTriggerHandlerHelper {

    public static void preventAddMoreThanOne(List<PlanilhaOrcamentaria__c> triggerNew){
        
        Set<Id> idsPlanilhas = new Set<Id>();
        Projeto__c proj = new Projeto__c();
        
        for(PlanilhaOrcamentaria__c plan: triggerNew){
            idsPlanilhas.add(plan.Id);
        }
       
        //List<PlanilhaOrcamentaria__c> planilhas = [SELECT Id, PlanilhaOrcamentariaProjeto__c FROM PlanilhaOrcamentaria__c WHERE Id IN : idsPlanilha AND PlanilhaOrcamentariaProjeto__c != null];
        
        Integer counter = [SELECT COUNT() FROM PlanilhaOrcamentaria__c WHERE PlanilhaOrcamentariaProjeto__c != null];
        
        //system.debug('planilhas:: ' + planilhas);
        
        for(PlanilhaOrcamentaria__c planilha: triggerNew){
            if(counter != 1)
            	planilha.addError('Um Projeto não pode ter mais de uma Planilha Orçamentária');
        }
        
        // verificar se ja existe planilha adicionada no projeto, caso tenha, deletar a nova 
    }
    
    
    // daqui pra baixo ja funciona
    public static void preventDeletion(List<PlanilhaOrcamentaria__c> triggerOld){
        for(PlanilhaOrcamentaria__c planilha: triggerOld){
            planilha.addError('Uma Planilha Orçamentária não pode ser deletada');
        }
    }
}