TCC/TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/PlanilhaOrcamentaria__c.object-meta.xml
<CustomObject>
    <description>Planilhas orçamentárias presentes em cada projeto</description>
    <label>Planilha Orçamentária</label>
    <nameField>
        <label>Planilha Orçamentária</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planilhas Orçamentárias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição da Planilha Orçamentária</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/fields/PlanilhaOrcamentariaProjeto__c.field-meta.xml
<CustomField>
    <fullName>PlanilhaOrcamentariaProjeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Planilha Orçamentária do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Planilha Orcamentária do Projeto</relationshipLabel>
    <relationshipName>PlanilhaOrcamentariaProjeto</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Administrar os projetos sociais das instituições não governamentais beneficiadas pelo software</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/Projeto__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

TCC/TCC/force-app/main/default/classes/PlanilhaOrcamentariaLWCController.cls
public with sharing class PlanilhaOrcamentariaLWCController {

    @AuraEnabled
    public static List<PlanilhaOrcamentariaVO> getPlanilha(String recordId){
        List<PlanilhaOrcamentaria__c>  listPlanilhas = PlanilhaOrcamentariaDAO.get(recordId);
        List<PlanilhaOrcamentariaVO> listPlanVO = new List<PlanilhaOrcamentariaVO>();
        
        String urlDomain = Url.getOrgDomainUrl().toExternalForm();

        for(PlanilhaOrcamentaria__c plan: listPlanilhas){
            listPlanVO.add(new PlanilhaOrcamentariaVO(plan.Id, plan.Name, plan.Descricao__c, plan.PlanilhaOrcamentariaProjeto__c, plan.PlanilhaOrcamentariaProjeto__r.Name, urlDomain));
        }
        return listPlanVO;
    }
}