TCC/TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/PlanilhaOrcamentaria__c.object-meta.xml
<CustomObject>
    <description>Planilhas orçamentárias presentes em cada projeto</description>
    <label>Planilha Orçamentária</label>
    <nameField>
        <label>Planilha Orçamentária</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planilhas Orçamentárias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição da Planilha Orçamentária</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/fields/PlanilhaOrcamentariaProjeto__c.field-meta.xml
<CustomField>
    <fullName>PlanilhaOrcamentariaProjeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Planilha Orçamentária do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Planilha Orcamentária do Projeto</relationshipLabel>
    <relationshipName>PlanilhaOrcamentariaProjeto</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Administrar os projetos sociais das instituições não governamentais beneficiadas pelo software</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/Projeto__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

TCC/TCC/force-app/main/default/classes/ProjetoTriggerHandlerHelper.cls
public without sharing class ProjetoTriggerHandlerHelper {

    public static void insertRelatedPlanilhaInProjeto(List<Projeto__c> triggerNew){
        PlanilhaOrcamentaria__c planilhaProjeto = new PlanilhaOrcamentaria__c();
     
        for(Projeto__c proj: triggerNew){
            planilhaProjeto.PlanilhaOrcamentariaProjeto__c = proj.Id;
            planilhaProjeto.Name = 'Planilha Orçamentária do Projeto ' + proj.Name;
            
            if(proj.Descricao__c != null)
                planilhaProjeto.Descricao__c = 'Descrição da Planilha Orçamentária com base em ' + proj.Descricao__c;
        }
        
        try{
             Database.insert(planilhaProjeto);
        }catch(Exception e){
            system.debug(e.getMessage() + ' ' + e.getTypeName());
        }
    }
}