TCC/TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/PlanilhaOrcamentaria__c.object-meta.xml
<CustomObject>
    <description>Planilhas orçamentárias presentes em cada projeto</description>
    <label>Planilha Orçamentária</label>
    <nameField>
        <label>Planilha Orçamentária</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planilhas Orçamentárias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Administrar os projetos sociais das instituições não governamentais beneficiadas pelo software</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Receitas__c/Receitas__c.object-meta.xml
<CustomObject>
    <label>Receita</label>
    <nameField>
        <label>Receitas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/Receitas__c/fields/DataReceita__c.field-meta.xml
<CustomField>
    <fullName>DataReceita__c</fullName>
    <label>Data do Recebimento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Receitas__c/fields/Fonte__c.field-meta.xml
<CustomField>
    <fullName>Fonte__c</fullName>
    <label>Fonte</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Receitas__c/fields/ReceitaPlanilhaOrcamentaria__c.field-meta.xml
<CustomField>
    <fullName>ReceitaPlanilhaOrcamentaria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Planilha Orçamentária</label>
    <referenceTo>PlanilhaOrcamentaria__c</referenceTo>
    <relationshipLabel>Receitas</relationshipLabel>
    <relationshipName>Receitas</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/force-app/main/default/objects/Receitas__c/fields/ReceitasProjeto__c.field-meta.xml
<CustomField>
    <fullName>ReceitasProjeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receitas do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Receitas</relationshipLabel>
    <relationshipName>ReceitasProjeto</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Receitas__c/fields/ValorReceita__c.field-meta.xml
<CustomField>
    <fullName>ValorReceita__c</fullName>
    <label>Valor da Receita</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

TCC/TCC/force-app/main/default/classes/ReceitasDAO.cls
public with sharing class ReceitasDAO implements DAO{

    public static List<Receitas__c> get(String recordId){
        return [SELECT Id, Name, DataReceita__c, Fonte__c, ReceitaPlanilhaOrcamentaria__c, ReceitaPlanilhaOrcamentaria__r.Name, ReceitasProjeto__c, ReceitasProjeto__r.Name, ValorReceita__c FROM Receitas__c WHERE Id =: recordId];
    }
    
    public static List<Receitas__c> getAllByMonth(Decimal mes){
        return [SELECT Id, ValorReceita__c, Mes__c FROM Receitas__c WHERE Mes__c =: mes];
    }
    
    public static List<Receitas__c> getAll(){
        return [SELECT Id, ValorReceita__c FROM Receitas__c];
    }
}