TCC/TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/PlanilhaOrcamentaria__c.object-meta.xml
<CustomObject>
    <description>Planilhas orçamentárias presentes em cada projeto</description>
    <label>Planilha Orçamentária</label>
    <nameField>
        <label>Planilha Orçamentária</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planilhas Orçamentárias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/PlanilhaOrcamentaria__c/fields/PlanilhaOrcamentariaProjeto__c.field-meta.xml
<CustomField>
    <fullName>PlanilhaOrcamentariaProjeto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Planilha Orçamentária do Projeto</label>
    <referenceTo>Projeto__c</referenceTo>
    <relationshipLabel>Planilha Orcamentária do Projeto</relationshipLabel>
    <relationshipName>PlanilhaOrcamentariaProjeto</relationshipName>
    <type>Lookup</type>
</CustomField>

TCC/TCC/force-app/main/default/classes/PlanilhaOrcamentariaTriggerHandlerHelper.cls
public with sharing class PlanilhaOrcamentariaTriggerHandlerHelper {

    public static void preventAddMoreThanOne(Map<Id, PlanilhaOrcamentaria__c> mapTriggerNew){
        for(PlanilhaOrcamentaria__c plan : mapTriggerNew.values()){
            if(plan.PlanilhaOrcamentariaProjeto__c == null)
                plan.addError('bosta vaca');
        }
    }
    
    public static void preventDeletion(List<PlanilhaOrcamentaria__c> triggerOld){
        for(PlanilhaOrcamentaria__c planilha: triggerOld){
            planilha.addError('Uma Planilha Orçamentária não pode ser deletada');
        }
    }
}