TCC/TCC/force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <description>Administrar os projetos sociais das instituições não governamentais beneficiadas pelo software</description>
    <label>Projeto</label>
    <nameField>
        <label>Nome do Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TCC/TCC/force-app/main/default/objects/Projeto__c/fields/Atendidos__c.field-meta.xml
<CustomField>
    <fullName>Atendidos__c</fullName>
    <formula>BeneficiariosDiretos__c  +  BeneficiariosIndiretos__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Atendidos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TCC/force-app/main/default/objects/Projeto__c/fields/DataInicioProjeto__c.field-meta.xml
<CustomField>
    <fullName>DataInicioProjeto__c</fullName>
    <label>Data de Início do Projeto</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/force-app/main/default/objects/Projeto__c/fields/DataTerminoProjeto__c.field-meta.xml
<CustomField>
    <fullName>DataTerminoProjeto__c</fullName>
    <label>Data de Término do Projeto</label>
    <type>Date</type>
</CustomField>

TCC/force-app/main/default/objects/Projeto__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

TCC/force-app/main/default/objects/Projeto__c/fields/PeriodoProjeto__c.field-meta.xml
<CustomField>
    <fullName>PeriodoProjeto__c</fullName>
    <label>Período</label>
    <type>Date</type>
</CustomField>

TCC/TCC/force-app/main/default/objects/Projeto__c/fields/StatusProjeto__c.field-meta.xml
<CustomField>
    <fullName>StatusProjeto__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando Resposta</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TCC/TCC/force-app/main/default/classes/ProjetosLWCController.cls
public with sharing class ProjetosLWCController {

    @AuraEnabled
    public static List<ProjetoVO> getDadosProjetos(String recordId){
     	List<ProjetoVO> listProjetoVO = new List<ProjetoVO>();
        List<Projeto__c> projetos = ProjetoDAO.get(recordId);

        for(Projeto__c proj: projetos){
            listProjetoVO.add(new ProjetoVO(proj.Id, proj.Name, proj.Descricao__c, proj.Atendidos__c, proj.DataInicioProjeto__c,
                                           proj.DataTerminoProjeto__c != null ? proj.DataTerminoProjeto__c : null, 
                                           proj.PeriodoProjeto__c != null ? proj.PeriodoProjeto__c : null,
                                           proj.StatusProjeto__c));
        }
        return listProjetoVO;
    }
}