TCC/force-app/main/default/objects/Receitas__c/Receitas__c.object-meta.xml
<CustomObject>
    <label>Receita</label>
    <nameField>
        <label>Receitas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/Receitas__c/fields/DataReceita__c.field-meta.xml
<CustomField>
    <fullName>DataReceita__c</fullName>
    <label>Data do Recebimento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/force-app/main/default/classes/ReceitasTriggerHandlerHelperTest.cls
@isTest
private class ReceitasTriggerHandlerHelperTest {
    
    @testSetup
    static void makeData(){
        insert TestDataFactory.makeDespesa();
    }
    
    @isTest
    static void fillMonthFieldTest(){
        
        List<Receitas__c> listReceitas = [SELECT Id, Mes__c, DataReceita__c FROM Receitas__c];
        
        Test.startTest();
        ReceitasTriggerHandlerHelper.fillMonthField(listReceitas);
        Test.stopTest();
    }
}