TCC/force-app/main/default/objects/Receitas__c/Receitas__c.object-meta.xml
<CustomObject>
    <label>Receita</label>
    <nameField>
        <label>Receitas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TCC/force-app/main/default/objects/Receitas__c/fields/DataReceita__c.field-meta.xml
<CustomField>
    <fullName>DataReceita__c</fullName>
    <label>Data do Recebimento</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TCC/force-app/main/default/classes/ReceitasTriggerHandlerHelper.cls
public with sharing class ReceitasTriggerHandlerHelper {
    
    public static void fillMonthField(List<Receitas__c> triggerNew){

        Integer mesReceita;
        
        List<Receitas__c> rList = [SELECT Id, Mes__c, DataReceita__c FROM Receitas__c WHERE Id IN: triggerNew];
        List<Receitas__c> rToUpdate = new List<Receitas__c>();

        for(Receitas__c receita : rList){
            mesReceita = receita.DataReceita__c.month();
            receita.Mes__c = mesReceita;
            system.debug('mes da receita ' + receita.mes__c);
            rToUpdate.add(receita);
        }
        update rToUpdate;
    }
}